# Generated by Django 6.0.1 on 2026-02-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('immatriculation', models.CharField(max_length=20)),
                ('nom_chauffeur', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_recette', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
